### ISSUE TITLE
微博授权后 redirect 服务器报错

### ISSUE THREAD

**Issue by AlwaysSkylll** [Werb/Pixel-Web#1]
微博授权后 redirect 服务器报错，手动修改api_config.js的地址为本地，提示redirecturl dismatch，是微博授权绑定了跳转的地址了吧，然后你服务器没开？不能在我本地浏览

**Comment by werbhelius** [comment]
@AlwaysSkylll 
1. 需要在微博控制台那里绑定回调地址，且不能写localhost，必须是真实地址
2. 所以你可以去微博建一个应用，很快的分分钟搞定，看一下这个tips https://github.com/Werb/Pixel-Web#tips
3. 服务器地址在这里 https://github.com/Werb/Pixel-Api  clone 下来  `npm install` `node app.js` 本地服务器就跑起来了

**Comment by werbhelius** [comment]
Pixel-Api 服务器我已经部署到了 Heroku
在线 Server 地址 https://pixel-api.herokuapp.com/

**Comment by AlwaysSkylll** [comment]
好的。我去试试，刚好今天微博开发者审核也通过了。

**Comment by sufengyong** [comment]
请问为什么我在api-config.js里面改成我的ip地址还有微博上面授权页面回调地址也改成我的ip还是访问不了呢

**Comment by werbhelius** [comment]
@sfengyong 有什么提示访问不了？接口调用不成功还是没有登录界面？

**Comment by sufengyong** [comment]
一个空白页面写着Cannot GET /   
 appkey和appsecret还有回调地址都改成我自己的了还是不行，微博上面的授权设置也改了

**Comment by werbhelius** [comment]
@sfengyong 微博的登录界面可以出来么？

**Comment by sufengyong** [comment]
没有，npm run dev之后什么都没有直接显示Cannot GET,       方便上微博吗，我可以私信发截图
