### ISSUE TITLE
这个 列表页跳到后，再返回，滚动条位置 不能还原呀

### ISSUE THREAD

**Issue by peng-yin** [Werb/Pixel-Web#4]

**Comment by werbhelius** [comment]
@silverpeng  哪个列表页？ 跳哪里？ 还原什么状态？

**Comment by peng-yin** [comment]
主页 不是有很多微博么，滚动后，随便点一条，然后在返回，记录滚条位置，这个没实现吧

**Comment by werbhelius** [comment]
实现了啊 https://github.com/Werb/Pixel-Web/blob/master/src/router/router.js#L158-L213
