### ISSUE TITLE
主页接口数据请不回来哦

### ISSUE THREAD

**Issue by abaozhizhong** [Werb/Pixel-Web#5]
这个 token是有的，但是就是数据没请回来

GET
 https://pixel-api.herokuapp.com/statuses/home_timeline.json?access_token=XXXX&count=30&page=1
net::ERR_TIMED_OUT

我账户的已有接口没有/statuses/home_timeline.json   这个接口 。
希望能解决我的疑问，谢谢

**Comment by werbhelius** [comment]
@abaozhizhong http://open.weibo.com/wiki/2/statuses/home_timeline

**Comment by abaozhizhong** [comment]
但是我在这里
![temp](https://user-images.githubusercontent.com/22359458/29156126-c8d48120-7dd2-11e7-8cf4-2bf5a59b1e27.png)
没有看到这个接口,还是这个接口需要申请。。。 
我是直接改了api.config 就跑的
![temp2](https://user-images.githubusercontent.com/22359458/29156212-3d694c28-7dd3-11e7-906f-916bdcc11c61.png)
纳闷一直没能load出微博内容
![temp3](https://user-images.githubusercontent.com/22359458/29156254-6c809a7a-7dd3-11e7-9277-ff24547d1cbb.png)

**Comment by abaozhizhong** [comment]
![temp4](https://user-images.githubusercontent.com/22359458/29156835-746cd516-7dd6-11e7-8fc8-783cd7914875.png)
我也不知道为啥现在可以了,但还是得谢谢您☺

**Comment by werbhelius** [comment]
改了api.config 是什么意思？

**Comment by abaozhizhong** [comment]
抱歉，没能表述准确。修改了api-config.js  里面的 const key_config = {
    app_key: 'xxx',
    app_secret: 'xxx',
    redirect_uri: 'xxx'
}  谢谢您的回答，还有您提供的源码
