### ISSUE TITLE
clear localstorage 的判断，大神看看是不是有点瑕疵

### ISSUE THREAD

**Issue by jonnzer** [Werb/Pixel-Web#6]
![e5a3ad8f-81d3-4ee3-8bcf-d739c020454e](https://user-images.githubusercontent.com/21023707/30052606-9577d382-9258-11e7-8187-5eb0d5d982b4.png)
不应该是有这个token存在，才clear掉吗？为什么判断是没有获取token时，clear掉这个localStorage？还清解答一番

**Comment by werbhelius** [comment]
是的应该是判断不为空的时候删除 token ，已修正，非常感谢 🙏 ！
